[package]
name = "warwick-thesis"
version = "0.1.7"
compiler = "0.14.2"
entrypoint = "thesis.typ"
authors = ["Ari Biswas <tcs@randomwalks.xyz>"]
license = "MIT"
description = "A Typst thesis template for the University of Warwick."
repository = "https://github.com/abiswas3/typst-thesis-template"
keywords = ["thesis", "warwick", "phd", "university"]
categories = ["thesis"]
exclude = [
".git",
".gitignore",
"**/*.pdf",
]
